### ISSUE TITLE
Halt on uncommited changes for Docker deployments

### ISSUE THREAD

**Issue by lazzarello** [gxela/awsebcli#21]
I encountered an esoteric detail that appears like a bug. It only occurs if multiple conditions are met.
1. `eb init` is run in a dir that is an existing git repository
2. Dockerun.aws.json is not committed into source control

Running `eb create` will always fail in this case, with output like 

`ERROR: Dockerfile and Dockerrun.aws.json are both missing, abort deployment`

Despite the existence of Dockerrun.aws.json on my local disk. There is also a warning which happens prior to the error, informing me that "I have uncommitted changes".

In this case, the uncommitted changes are crucial for a successful deployment, though they contain information I would not want included in a public project. To add further confusion, the file `.elasticbeanstalk/config.yml` has an option that reads `sc: git`. If I change that to `sc: null` I expect that my uncommitted changes will no longer be a problem. This expectation is not met. I continue to get output from `eb create` about uncommitted changes.

This confusion would be eliminated if the utility would halt prior to warning about the uncommitted changes. Creating a Docker based environment without any instructions for Docker seems like a bug.

**Comment by sibelius** [comment]
@lazzarello did u solve your problem?

**Comment by lazzarello** [comment]
yeah, I'll close this.
