### ISSUE TITLE
Document deploy artifact

### ISSUE THREAD

**Issue by JuanCaicedo** [gxela/awsebcli#4]
According to [this discussion](https://forums.aws.amazon.com/message.jspa?messageID=597304), it's possible to deploy a manually created zip file to AWS from the EB CLI. I've been able to get it to work very inconsistently, and haven't found any documentation about it. It would be great if it was documented somewhere!

**Comment by mull** [comment]
It works frustratingly inconsistently for me as well. It seems to only randomly detect the artifact configuration.

**Comment by mull** [comment]
@gxela what is the state of this repo? Do you intend to continue maintaining it or should it be forked/handed over?

**Comment by gxela** [comment]
Fork it if you want. I didn't find a awsebcli lib on github so i imported it from an alternate source, I was gonna add some missing functionality a while ago but I got distracted with some other deployments with chef and haven't used awsebcli since then
